[versions]
agp = "9.2.0"
flatbuffersJava = "25.2.10"
kotlin = "2.3.20"
dexkit = "2.2.0"
libxposed = "102.0.0"
annotation = "1.10.0"
gson = "2.13.2"
kotlinxCoroutinesAndroid = "1.10.2"
fuel = "3.0.0-alpha04"
junit = "6.0.3"
jadx = "1.5.5"
slf4j = "2.0.17"
material = "1.13.0"

[libraries]
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }
flatbuffers-java = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffersJava" }
libxposed = { group = "org.lsposed.libxposed", name = "api", version.ref = "libxposed" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
fuel = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "fuel" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
jadx-core = { group = "io.github.skylot", name = "jadx-core", version.ref = "jadx" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version = "1.11.0" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

