name: api-compat build

on:
  push:
    branches: [ "api-compat" ]
    paths-ignore: 
      - ".github/**"
      - ".gitignore"
      - ".gitmodules"
      - "README.md"
      - "DEVELOPMENT.md"
  workflow_dispatch:
  pull_request:
    branches: [ "api-compat" ]
    paths-ignore: 
      - ".github/**"
      - ".gitignore"
      - ".gitmodules"
      - "README.md"
      - "DEVELOPMENT.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get random number
      id: random
      run: echo "NUMBER=$(shuf -i 1-10000 -n 1)" >> $GITHUB_OUTPUT

    - name: Build Release
      run: ./gradlew assembleUniversalRelease -PPACKAGE_NAME_SEED=${{ steps.random.outputs.NUMBER }}

    - name: Upload a Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rvxp-ci-release-apk
        path: |
          app/build/outputs/apk/universal/release
          app/build/outputs/mapping/universalRelease/mapping.txt

    - name: Create AutoBuild Release
      run: |
        GIT_DESCRIBE=$(git rev-parse --short HEAD)
        GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=format:%y%m%d)
        cd app/build/outputs/apk/universal/release/
        mv app-universal-release.apk ReVancedXposedFESpotify-${GIT_COMMIT_DATE}.apk
        gh release delete api-comapt --yes || true
        gh release create api-compat ReVancedXposedFESpotify-${GIT_COMMIT_DATE}.apk --title "api-compat ${GIT_COMMIT_DATE}" --notes "Commit ${GIT_DESCRIBE}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
